spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoreconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: tigerli199351.
    driver-class: com.mysql.jdbc.Driver